### ISSUE TITLE
Offline Mode Crashes in Newer Releases

### ISSUE THREAD

**Issue by KJCavin** [smatechnologies/opcon-web-installer#5]
Our environment has no internet access so we use the OWI in offline mode to assist in installing upgrades. However, release 1.6 is the last working release. Anything newer will crash when click the Next button with the Offline Mode box checked. I tested this with 1.10 and the behavior is the same. I seem to recall an issue early on where OWI was still attempting to do an online check while in offline mode, but I'm not 100% sure of that. Support for OpConMFT is missing from the 1.6 installer, which isn't a huge deal.

```
Application: OpCon Web Installer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.First[[SMA.OpCon.WebInstaller.Products.Actions.ActionType, OpCon Web Installer, Version=1.10.0.0, Culture=neutral, PublicKeyToken=null]](System.Collections.Generic.IEnumerable`1<SMA.OpCon.WebInstaller.Products.Actions.ActionType>, System.Func`2<SMA.OpCon.WebInstaller.Products.Actions.ActionType,Boolean>)
   at SMA.OpCon.WebInstaller.Products.Actions.AvailableActionGovernor.CalculateDefaultAction(Package, SMA.OpCon.WebInstaller.Products.Actions.ActionType ByRef, PackageVersion ByRef)
   at SMA.OpCon.WebInstaller.Products.Actions.AvailableActionGovernor.PopulateActions(System.Collections.Generic.IEnumerable`1<Package>)
   at OpCon_Web_Installer.WindowMain+<NavigateForward>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at OpCon_Web_Installer.App.Main()
```

```
Faulting application name: OpCon Web Installer.exe, version: 1.10.0.0, time stamp: 0x810d11a9
Faulting module name: KERNELBASE.dll, version: 10.0.14393.6897, time stamp: 0x660f5eec
Exception code: 0xe0434352
Fault offset: 0x0000000000026ea8
Faulting process id: 0x7b8
Faulting application start time: 0x01daa6ffd6a9f361
Faulting application path: E:\OpCon Installation\OWI-1.10\OpCon Web Installer.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 90739597-b2bd-4d51-836c-7fe37bb6e260
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by hblake316** [comment]
Hi, thank you for reporting this and for the detailed stack trace.

This issue with offline mode crashing when clicking Next was resolved in version 1.13.0 (and possibly earlier, though 1.13.0 is confirmed stable). 

We recommend upgrading to OWI 1.13.0 or later, which includes a fix for this issue as well as support for OpConMFT.

Please let us know if you still encounter any problems after upgrading — and thank you again for helping improve the installer!
